services:
  rails:
    build:
      dockerfile: dev.dockerfile
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
